// Generated by gencpp from file the_game/Update.msg
// DO NOT EDIT!


#ifndef THE_GAME_MESSAGE_UPDATE_H
#define THE_GAME_MESSAGE_UPDATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>

namespace the_game
{
template <class ContainerAllocator>
struct Update_
{
  typedef Update_<ContainerAllocator> Type;

  Update_()
    : vectors()  {
    }
  Update_(const ContainerAllocator& _alloc)
    : vectors(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Vector3_<ContainerAllocator> >::other >  _vectors_type;
  _vectors_type vectors;




  typedef boost::shared_ptr< ::the_game::Update_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::the_game::Update_<ContainerAllocator> const> ConstPtr;

}; // struct Update_

typedef ::the_game::Update_<std::allocator<void> > Update;

typedef boost::shared_ptr< ::the_game::Update > UpdatePtr;
typedef boost::shared_ptr< ::the_game::Update const> UpdateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::the_game::Update_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::the_game::Update_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace the_game

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'the_game': ['/home/cc/ee106a/fa16/class/ee106a-act/ros_workspaces/ee106a-patrol-game/src/the_game/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::the_game::Update_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::the_game::Update_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::the_game::Update_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::the_game::Update_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::the_game::Update_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::the_game::Update_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::the_game::Update_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e70d69b80b6619295db7fb48376314f";
  }

  static const char* value(const ::the_game::Update_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e70d69b80b66192ULL;
  static const uint64_t static_value2 = 0x95db7fb48376314fULL;
};

template<class ContainerAllocator>
struct DataType< ::the_game::Update_<ContainerAllocator> >
{
  static const char* value()
  {
    return "the_game/Update";
  }

  static const char* value(const ::the_game::Update_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::the_game::Update_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Vector3[] vectors\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::the_game::Update_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::the_game::Update_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vectors);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Update_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::the_game::Update_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::the_game::Update_<ContainerAllocator>& v)
  {
    s << indent << "vectors[]" << std::endl;
    for (size_t i = 0; i < v.vectors.size(); ++i)
    {
      s << indent << "  vectors[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "    ", v.vectors[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // THE_GAME_MESSAGE_UPDATE_H
